### ISSUE TITLE
convert callbacks to promises

### ISSUE THREAD

**Issue by luisrudge** [Medium/medium-sdk-nodejs#10]
are you guys interested in a PR for that?

**Comment by majelbstoat** [comment]
Hi, 

Most node libraries and node itself are centered around the callback model, so we'll be sticking with that for a while. We use promises ourselves internally, and use `Q.nfcall()` where appropriate.

Might be appropriate to add support for both once the community is more heavily invested in ES6, but it's not a priority for right now.

Thanks for your understanding :)
