### ISSUE TITLE
Can't get Access Token 

### ISSUE THREAD

**Issue by udaiveerS** [Medium/medium-sdk-nodejs#15]
I have tried to use the SDK as well as do it myself, but no luck...

Attempt 1  

    var client = new medium.MediumClient({
      clientId: '132d940695be',
      clientSecret: 'af9aa97aa69364beb36225b79b231c882e537ca1'
    });

    var url = client.getAuthorizationUrl('secretState', 'https://q-apps.io/api/medium', [
      medium.Scope.BASIC_PROFILE, medium.Scope.PUBLISH_POST
    ]);

    console.log(url);

this is how i am trying to get access token 

    client.exchangeAuthorizationCode('f79dd700c137', 'https://q-apps.io/api/medium', function (err, token) {
      console.log(err);
      console.log(token);
     });
but i get the following 

    { errors: [ { message: 'Authorization code not found.', code: 6016 } ] }

I am testing this on localhost, I don't know why this is not working.

**Comment by heldtogether** [comment]
@udaiveerS  Authorization codes can only be used once and expire. Maybe try to generate a new authorization code and see if you have you any success. Your first approach looks ok to me otherwise.

**Comment by udaiveerS** [comment]
I was able to get the Access and Refresh tokens! There was a small but in the source code and also a little bit inconsistency in the documentation. I will do a pull request tomorrow. I haven't done one before so it should be fun. I think it is like one word or something. Thanks for the help.

**Comment by Innarticles** [comment]
@udaiveerS How did you get the token. 
What does url return?

**Comment by udaiveerS** [comment]
The url does not really matter if you just want to get the token just for you. It is simply what you are redirected to by medium and the url that you are redirected to has a access token.

**Comment by lnmunhoz** [comment]
@udaiveerS Can you give some example? I'm trying this:
```js
 var url = md.getAuthorizationUrl('secretState', redirectUrl, [
    medium.Scope.BASIC_PROFILE, medium.Scope.PUBLISH_POST
  ])
  md.exchangeAuthorizationCode(url, redirectUrl, function(err, token) {
    console.log(url);
    console.log(token);
    md.getUser(function(err, user) {
      res.json({
        err: err,
        user: user
      })
    });
  })
```

But I'm getting his error:
```js
Object {err: Object, user: null}
err: Object
code: 6000
message: "An access token is required."
```

How to set the accessToken?

**Comment by udaiveerS** [comment]
```
var medium = require('medium-sdk')

var client = new medium.MediumClient({
  clientId: 'YOUR_CLIENT_ID',
  clientSecret: 'YOUR_CLIENT_SECRET'
})

var redirectURL = 'https://yoursite.com/callback/medium'; 

var url = client.getAuthorizationUrl('secretState', redirectURL, [
  medium.Scope.BASIC_PROFILE, medium.Scope.PUBLISH_POST
])

console.log(url);
```

You can literally leave the redirectURL exactly the same. After having your client ID and and Secret pasted in. Console.log the url and click on it. After you click on in your browser will ask you to login to Medium and redirect you to this url but with a query parameter 
`https://yoursite.com/callback/medium?authorization_code=XXXXXXXXX`
You need to copy that authorization_code into this piece of code. 
```
client.exchangeAuthorizationCode('YOUR_AUTHORIZATION_CODE', redirectURL, function (err, token) {
  client.getUser(function (err, user) {
    client.createPost({
      userId: user.id,
      title: 'A new post',
      contentFormat: medium.PostContentFormat.HTML,
      content: '<h1>A New Post</h1><p>This is my new post.</p>',
      publishStatus: medium.PostPublishStatus.DRAFT
    }, function (err, post) {
      console.log(token, user, post)
    })
  })
})
```

And now run this code only once to get the Token. Token object has all the tokens you need for medium api. 

**Recap**
The Token object has 2 tokens, A refresh and a access token. Access token expires every 60. You have to use refresh token to update it before then. Refresh token does not expire. 
AUTHORIZATION_CODE allows you to get access to the Token object, but AUTHORIZATION_CODE can only be used once and you will need a new one if you lose your refresh token.

**Comment by BobAleena** [comment]
I'm using a self issued token, but getting an error. In the above code, would I replace 'YOUR_AUTHORIZATION_CODE' with my self issued token?
The error that I am getting is: 'Authorization code not found'

**Comment by selfup** [comment]
Yea curious on how to use use this with only a self-issued access token. Trying to build a Jekyll like equivalent that just published to Medium, no need to authenticate via OAuth.

**Comment by sbsashu** [comment]
how to get authentication keys from medium may i nkow
