### ISSUE TITLE
The NPM module need to be updated 

### ISSUE THREAD

**Issue by udaiveerS** [Medium/medium-sdk-nodejs#16]
![image](https://cloud.githubusercontent.com/assets/12993700/12612810/42c9a3fe-c4aa-11e5-9723-8a261483e433.png)

VS what is in NPM 

![image](https://cloud.githubusercontent.com/assets/12993700/12612858/963eeb84-c4aa-11e5-81db-faa8a5a23f90.png)

The payload.data was causing errors to be thrown because explanation #8. This was causing some headaches until I decided to check git and it was fixed. An update to NPM is needed.

**Comment by huckphin** [comment]
Thank you for the report. Good catch. Will update.

**Comment by huckphin** [comment]
Version `0.0.2` has been published with the changes from master.
