### ISSUE TITLE
Readme.md provides wrong information

### ISSUE THREAD

**Issue by shobhitic** [Medium/medium-sdk-nodejs#5]
According to Readme file, we need to run `npm install medium-sdk-nodejs` and then `var medium = require('medium-sdk-nodejs')`.

Both of them don't work and correct usage is `npm install medium-sdk` and then `var medium = require('medium-sdk')`.

Not giving a pull request because it'll take time to register.

**Comment by abirqasem** [comment]
Thanks a lot shobhitic  it fixed the registry issue.
