### ISSUE TITLE
npm fails

### ISSUE THREAD

**Issue by abirqasem** [Medium/medium-sdk-nodejs#6]
'medium-sdk-nodejs' is not in the npm registry.

**Comment by lambtron** [comment]
The proper npm name is `medium-sdk`:

https://www.npmjs.com/package/medium-sdk

**Comment by abirqasem** [comment]
thanks!

**Comment by majelbstoat** [comment]
Bah, thanks all, I'll fix this.

**Comment by majelbstoat** [comment]
Fixed by #7. Thanks for the report!
