### ISSUE TITLE
_makeRequest calls back undefined

### ISSUE THREAD

**Issue by jakeapeters** [Medium/medium-sdk-nodejs#8]
At line 275 `callback(null, payload.data)` actually calls back `(null, undefined)`, which causes a TypeError later when trying to get the `access_token`.

May be conflicting with body-parser - my payload is the actual data already. Changing this to `callback(null, payload)` has the expected behaviour.

**Comment by AdityaShirole** [comment]
at line 231, in "this._accessToken = data.accessToken" data.accessToken is undefined. Changing it to data.access_token fixes it.

**Comment by majelbstoat** [comment]
Hey, sorry for the slow reply. I don't actually understand this just yet. The response envelope for API requests looks like this (for example):

`{"data": {"id": "xxx", "name": "Jamie"}}`

So, I'm not sure how `payload = JSON.parse(body)` would give direct access to the data, without doing `payload.data`

In fact, I've written a test client which has this working. Can you supply a minimal test case that illustrates the failure?

**Comment by majelbstoat** [comment]
... and immediately after writing that, I understand the problem.

The token endpoint has a different envelope to every other endpoint (thanks OAuth2), so this needs to be special-cased. This should be straightforward.

Thanks for the report!

**Comment by jakeapeters** [comment]
No worries :) OAuth2's trying to make you look bad!

**Comment by majelbstoat** [comment]
Fixed in #13.
